### ISSUE TITLE
How to run 3D demo?

### ISSUE THREAD

**Issue by ueoo** [ebirenbaum/ParticleSolver#2]
Hi @ebirenbaum , thanks for this code base, I am new to physics simulation.
Could you please tell me how to run the 3D demo as the images in README.md?

**Comment by LoganBarnes** [comment]
This was a fairly rushed school project we threw together in 2015. We don't maintain it. It's unlikely it would be easy to get this running on a modern system without some updates to the build system. Especially the 3D version since it includes some hacked together CUDA and OpenGL libraries.

It's probably for the best though. There are definitely better libraries out there for this kind of thing.

**Comment by ueoo** [comment]
I see, thanks for your reply.

**Comment by hologerry** [comment]
Hi @LoganBarnes , as you mentioned, this was a school project. May I ask could you please share the project report, if it's possible? 
Thanks a lot.
